/**
 * Copyright (2019, ) Institute of Software, Chinese Academy of Sciences
 */
package io.github.webfrk.orm.previous.examples;

import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;


/**
 * This code is generated by httpfrk-springboot-orm project
 *
 */
@Repository
public interface UserOrm extends CrudRepository<User, Long>, PagingAndSortingRepository<User, Long> {

	<S extends User> S save(@Param("user") User user);

}